implemented contact create view
taavitaivere/Laravel-CRUD pull request #1
Opened 2022-05-02 08:22 UTC by kadimarss

2022-05-02 11:33 UTC, JurgenMik commented on app/Http/Controllers/ContactController.php
> +
Is this new line necessary?

2022-05-02 11:34 UTC, JurgenMik commented on resources/js/Pages/Contact/Create.js
> +
Is this new line necessary?

2022-05-02 11:38 UTC, JurgenMik commented on resources/js/Pages/Contact/Create.js
> +                            <div>
It is suggested to use white space before the element:

```suggestion
                            <div className="mb-4">
```

2022-05-02 11:39 UTC, JurgenMik commented on resources/js/Pages/Contact/Create.js
> +                            <div className="mt-4">
It is suggested to use white space before the element:
```suggestion
                            <div className="mb-4">
```

2022-05-02 11:46 UTC, JurgenMik commented on resources/js/Pages/Contact/Create.js
> +                                </Button>
Make the form elements and the button same width?

2022-05-02 11:47 UTC, JurgenMik requested changes
Remove required validation from frontend components.
It is suggested to use white space before the element.

2022-05-03 06:32 UTC, kadimarss commented on resources/js/Pages/Contact/Create.js
> +
Yes.

2022-05-03 08:49 UTC, JurgenMik approved these changes

2022-05-03 10:13 UTC, merged